name: month_picker_dialog_2
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 0.6.2+1
homepage: https://github.com/Macacoazul01/month_picker_dialog_2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.7
  intl: 0.17.0

flutter:
